name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_reactions: yes
          plugin_reactions_limit: 9999                # Compute reactions over last xxx issue comments
          plugin_reactions_days: 9999                 # Compute reactions on issue comments posted less than xxx days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot               # Ignore "bot" user
          plugin_followup: yes
          plugin_followup_sections: user #
          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_skyline: yes
          plugin_skyline_year: 0            # Set to 0 to display current year
          plugin_skyline_frames: 60         # Use 60 frames (half-loop)
          plugin_skyline_quality: 1         # Set image quality
          plugin_skyline_compatibility: yes # Support additional browsers (⚠️ increases file size and reduce optimization)
