name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year                       # Display full year instead of half year
          plugin_languages: yes
          plugin_languages_ignored: html, css                          # List of languages to ignore
          plugin_languages_skipped: nothing                            # List of repositories to skip
          plugin_languages_colors:  ""                                 # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                               # Hides all languages less than 2%
          plugin_languages_limit: 10                                   # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used          # Display most used and recently used languages stats
          plugin_languages_indepth: yes                                # Get indepth stats (see documentation before enabling)
          commits_authoring: ktnkk@oo@kiki.ooo                         # Surnames or email addresses used to identify your commits
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          config_timezone: Asia/Tokyo   # Set timezone
