name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
#           user: ktnkk
#           repo: ktnkk
#           committer_token: ${{ github.token }}
#           committer_branch: main
#           committer_message: Update metrics
#           filename: metrics.svg
          config_timezone: Asia/Tokyo
          config_gemoji: yes
          config_twemoji: yes
          config_display: large
          config_padding: 0, 5%
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_reactions: yes
          plugin_reactions_limit: 200                # Compute reactions over last xxx issue comments
          plugin_reactions_days: 200                 # Compute reactions on issue comments posted less than xxx days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot               # Ignore "bot" user
#           plugin_followup: yes
#           plugin_followup_sections: user #
#           plugin_achievements: yes
#           plugin_achievements_threshold: B       # Display achievements with rank B or higher
#           plugin_achievements_secrets: yes       # Display unlocked secrets achievements
#           plugin_achievements_ignored: octonaut  # Hide octonaut achievement
#           plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga             # Display both animes and mangas
          plugin_anilist_sections: favorites, characters  # Display only favorites and characters sections
          plugin_anilist_limit: 2                         # Limit to 2 entry per section (characters section excluded)
          plugin_anilist_shuffle: yes                     # Shuffle data for more varied outputs
          plugin_anilist_user: .user.login                # Use same username as GitHub login
          plugin_anilist_limit_characters: 22             # Limit to 22 characters in characters section
#           plugin_music: yes
#           plugin_music_provider: spotify # Use Spotify as provider
#           plugin_music_mode: recent      # Set plugin mode
#           plugin_music_limit: 4          # Limit to 4 entries
#           plugin_music_played_at: yes    # Show timestamp (for spotify only)
#           plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
