name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_reactions: yes
          plugin_reactions_limit: 9999                # Compute reactions over last xxx issue comments
          plugin_reactions_days: 9999                 # Compute reactions on issue comments posted less than xxx days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot               # Ignore "bot" user
          plugin_people: yes
          plugin_people_types: followers, following  # Display followers and following sections
          plugin_people_limit: 28                    # Limit to 28 entries per section
          plugin_people_size: 28                     # Size in pixels of displayed avatars
          plugin_people_identicons: no               # Use avatars (do not use identicons)
          plugin_people_thanks: ""                   # Users that will be displayed in "thanks" section
          plugin_people_sponsors_custom: ""          # Users that will be displayed additionally in "sponsors" section
          plugin_people_shuffle: yes                 # Shuffle for varied output
