name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: nothing
          plugin_languages_colors:  ""
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_languages_limit: 10
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Tokyo
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_reactions: yes
          plugin_reactions_limit: 99999
          plugin_reactions_days: 99999
          plugin_reactions_details: count, percentage
          plugin_reactions_ignored: bot
          plugin_people: yes
          plugin_people_types: followers, thanks
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_identicons: no
          plugin_people_thanks: lowlighter, octocat
          plugin_people_sponsors_custom: octocat
          plugin_people_shuffle: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_traffic: yes
          plugin_stargazers: yes
          plugin_projects: yes
          plugin_projects_repositories: ktnkk/
          plugin_projects_limit: 4
          plugin_projects_descriptions: yes
          plugin_achievements: yes
          plugin_achievements_threshold: A
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0
   
