name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_introduction: no
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Tokyo
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_reactions: yes
          plugin_reactions_limit: 99999
          plugin_reactions_days: 99999
          plugin_reactions_details: count, percentage
          plugin_reactions_ignored: bot
          plugin_people: yes
          plugin_people_thanks: octocat
          plugin_people_shuffle: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_lines: no
          plugin_traffic: yes
          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_achievements_threshold: A
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0
